const vintageRestricted = loadVintageRestricted();
const bans = loadBans(loadRawBans);
const extendedBans = loadBans(loadRawExtendedBans);

chrome.runtime.onMessage.addListener(
    (request, sender, sendResponse) => {
        if (!request.hasOwnProperty('action')) {
            console.error('Received request without mandatory action property.', request);
            return;
        }
        switch (request.action) {
            case 'get/ban/list':
                getBanlist(sendResponse);
                return;
            case 'get/ban/card':
                getBanStatus(request.cardName, sendResponse);
                return;
            default:
                console.error('Unknown action "' + request.action + '" in request.', request);
                return;
        }
    },
);

function getBanStatus(cardName, sendResponse) {
    if (bans.hasOwnProperty(cardName)) {
        sendResponse({banStatus: 'banned', formats: bans[cardName]});
    }

    if (extendedBans.hasOwnProperty(cardName)) {
        sendResponse({banStatus: 'extended', formats: extendedBans[cardName]});
    }

    sendResponse({banStatus: null});
}

function getBanlist(sendResponse) {
    sendResponse(
        {
            bans: bans,
            extended: extendedBans,
        });
}

function loadBans(fn) {
    let bans = {};
    fn().forEach(ban => {
        // Filter out any vintage restricted cards, as they should
        // appear as "not legal" and neither 'banned' nor 'extended'
        if (vintageRestricted.hasOwnProperty(ban.name)) return;

        bans[ban.name] = ban.formats;
    });
    return bans;
}

function loadRawBans() {
    // @formatter:off
    return [
        {"name":"Absorb", "formats":{"Pioneer": 0.13}},
        {"name":"Adeline, Resplendent Cathar", "formats":{"Standard": 0.17}},
        {"name":"Aether Gust", "formats":{"Pioneer": 0.23}},
        {"name":"Alpine Moon", "formats":{"Pioneer": 0.14}},
        {"name":"Ancestral Recall", "formats":{"Vintage": 0.69}},
        {"name":"Anger of the Gods", "formats":{"Pioneer": 0.13}},
        {"name":"Archmage's Charm", "formats":{"Modern": 0.19}},
        {"name":"Archon of Emeria", "formats":{"Standard": 0.19}},
        {"name":"Augur of Bolas", "formats":{"Pauper": 0.13}},
        {"name":"Behold the Multiverse", "formats":{"Standard": 0.11}},
        {"name":"Black Lotus", "formats":{"Vintage": 0.83}},
        {"name":"Blood Fountain", "formats":{"Pauper": 0.12}},
        {"name":"Blood Moon", "formats":{"Modern": 0.19}},
        {"name":"Bloodchief's Thirst", "formats":{"Standard": 0.17}},
        {"name":"Blue Elemental Blast", "formats":{"Pauper": 0.25}},
        {"name":"Bolas's Citadel", "formats":{"Vintage": 0.29}},
        {"name":"Bonecrusher Giant", "formats":{"Pioneer": 0.16}},
        {"name":"Brainstorm", "formats":{"Legacy": 0.55, "Vintage": 0.67, "Pauper": 0.14}},
        {"name":"Brazen Borrower", "formats":{"Modern": 0.12, "Legacy": 0.29}},
        {"name":"Brutal Cathar", "formats":{"Standard": 0.23, "Pioneer": 0.13}},
        {"name":"Carpet of Flowers", "formats":{"Legacy": 0.13}},
        {"name":"Cast Down", "formats":{"Pauper": 0.16}},
        {"name":"Chain Lightning", "formats":{"Legacy": 0.13}},
        {"name":"Chainer's Edict", "formats":{"Pauper": 0.23}},
        {"name":"Chalice of the Void", "formats":{"Modern": 0.18, "Legacy": 0.12, "Vintage": 0.21}},
        {"name":"Chandra, Torch of Defiance", "formats":{"Pioneer": 0.15}},
        {"name":"Check for Traps", "formats":{"Standard": 0.15}},
        {"name":"Chromatic Star", "formats":{"Pauper": 0.20}},
        {"name":"Circle of Confinement", "formats":{"Standard": 0.14}},
        {"name":"Collector Ouphe", "formats":{"Legacy": 0.12}},
        {"name":"Consider", "formats":{"Pioneer": 0.14, "Modern": 0.13}},
        {"name":"Counterspell", "formats":{"Modern": 0.26, "Pauper": 0.26}},
        {"name":"Court of Cunning", "formats":{"Legacy": 0.10}},
        {"name":"Crop Rotation", "formats":{"Legacy": 0.11}},
        {"name":"Dack Fayden", "formats":{"Vintage": 0.24}},
        {"name":"Damping Sphere", "formats":{"Pioneer": 0.15}},
        {"name":"Dark Ritual", "formats":{"Legacy": 0.10}},
        {"name":"Daze", "formats":{"Legacy": 0.30}},
        {"name":"Deadly Dispute", "formats":{"Standard": 0.15, "Pauper": 0.21}},
        {"name":"Deafening Silence", "formats":{"Pioneer": 0.15}},
        {"name":"Deathrite Shaman", "formats":{"Vintage": 0.23}},
        {"name":"Delver of Secrets", "formats":{"Legacy": 0.23}},
        {"name":"Demonic Tutor", "formats":{"Vintage": 0.50}},
        {"name":"Dig Through Time", "formats":{"Vintage": 0.53}},
        {"name":"Disdainful Stroke", "formats":{"Standard": 0.26}},
        {"name":"Dispel", "formats":{"Pauper": 0.24}},
        {"name":"Doomskar", "formats":{"Standard": 0.20}},
        {"name":"Dovin's Veto", "formats":{"Pioneer": 0.18, "Modern": 0.11}},
        {"name":"Dragon's Rage Channeler", "formats":{"Modern": 0.18, "Legacy": 0.23}},
        {"name":"Dreadbore", "formats":{"Pioneer": 0.12}},
        {"name":"Dress Down", "formats":{"Modern": 0.22}},
        {"name":"Duress", "formats":{"Standard": 0.34, "Pioneer": 0.13, "Pauper": 0.27}},
        {"name":"Dust to Dust", "formats":{"Pauper": 0.23}},
        {"name":"Echoing Truth", "formats":{"Pauper": 0.16}},
        {"name":"Electrickery", "formats":{"Pauper": 0.24}},
        {"name":"Elite Spellbinder", "formats":{"Standard": 0.25, "Pioneer": 0.13}},
        {"name":"Elvish Mystic", "formats":{"Pioneer": 0.16}},
        {"name":"Emeria's Call", "formats":{"Standard": 0.29}},
        {"name":"End the Festivities", "formats":{"Legacy": 0.17}},
        {"name":"Endurance", "formats":{"Modern": 0.29, "Legacy": 0.23}},
        {"name":"Engineered Explosives", "formats":{"Modern": 0.35}},
        {"name":"Environmental Sciences", "formats":{"Standard": 0.11}},
        {"name":"Esika's Chariot", "formats":{"Standard": 0.13, "Pioneer": 0.13}},
        {"name":"Expedition Map", "formats":{"Modern": 0.10}},
        {"name":"Experimental Synthesizer", "formats":{"Pauper": 0.27}},
        {"name":"Expressive Iteration", "formats":{"Pioneer": 0.18, "Modern": 0.24, "Legacy": 0.26}},
        {"name":"Fable of the Mirror-Breaker", "formats":{"Pioneer": 0.12}},
        {"name":"Fading Hope", "formats":{"Standard": 0.13}},
        {"name":"Faerie Macabre", "formats":{"Legacy": 0.12}},
        {"name":"Faerie Seer", "formats":{"Pauper": 0.16}},
        {"name":"Faithless Looting", "formats":{"Pauper": 0.12}},
        {"name":"Farewell", "formats":{"Standard": 0.27, "Pioneer": 0.14}},
        {"name":"Fatal Push", "formats":{"Pioneer": 0.24, "Modern": 0.11}},
        {"name":"Fateful Absence", "formats":{"Standard": 0.13}},
        {"name":"Fiery Cannonade", "formats":{"Pauper": 0.25}},
        {"name":"Fiery Impulse", "formats":{"Pioneer": 0.13}},
        {"name":"Fire // Ice", "formats":{"Modern": 0.10}},
        {"name":"Flaring Pain", "formats":{"Pauper": 0.13}},
        {"name":"Flusterstorm", "formats":{"Legacy": 0.32, "Vintage": 0.67}},
        {"name":"Force of Negation", "formats":{"Modern": 0.24, "Legacy": 0.52, "Vintage": 0.63}},
        {"name":"Force of Vigor", "formats":{"Modern": 0.31, "Legacy": 0.17, "Vintage": 0.32}},
        {"name":"Force of Will", "formats":{"Legacy": 0.61, "Vintage": 0.78}},
        {"name":"Fury", "formats":{"Modern": 0.30}},
        {"name":"Galvanic Blast", "formats":{"Pauper": 0.33}},
        {"name":"Galvanic Iteration", "formats":{"Pioneer": 0.15}},
        {"name":"Gitaxian Probe", "formats":{"Vintage": 0.69}},
        {"name":"Glint Hawk", "formats":{"Pauper": 0.15}},
        {"name":"Go Blank", "formats":{"Standard": 0.26, "Pioneer": 0.16}},
        {"name":"Golden Egg", "formats":{"Pauper": 0.11}},
        {"name":"Goldspan Dragon", "formats":{"Standard": 0.14}},
        {"name":"Gorilla Shaman", "formats":{"Pauper": 0.29}},
        {"name":"Grafdigger's Cage", "formats":{"Legacy": 0.27, "Vintage": 0.31}},
        {"name":"Green Sun's Zenith", "formats":{"Legacy": 0.12}},
        {"name":"Guardian of Faith", "formats":{"Standard": 0.19}},
        {"name":"Gurmag Angler", "formats":{"Pauper": 0.19}},
        {"name":"Gush", "formats":{"Vintage": 0.23}},
        {"name":"Gut Shot", "formats":{"Pauper": 0.16}},
        {"name":"Hagra Mauling", "formats":{"Standard": 0.15}},
        {"name":"Hopeful Initiate", "formats":{"Standard": 0.17}},
        {"name":"Hullbreacher", "formats":{"Legacy": 0.18, "Vintage": 0.23}},
        {"name":"Hullbreaker Horror", "formats":{"Pioneer": 0.16}},
        {"name":"Hurkyl's Recall", "formats":{"Vintage": 0.31}},
        {"name":"Hydroblast", "formats":{"Pauper": 0.17}},
        {"name":"Ichor Wellspring", "formats":{"Pauper": 0.32}},
        {"name":"Infernal Grasp", "formats":{"Standard": 0.22}},
        {"name":"Intrepid Adversary", "formats":{"Standard": 0.16}},
        {"name":"Jace, the Mind Sculptor", "formats":{"Modern": 0.18, "Legacy": 0.11}},
        {"name":"Jwari Disruption", "formats":{"Standard": 0.17}},
        {"name":"Kolaghan's Command", "formats":{"Pioneer": 0.12}},
        {"name":"Kor Skyfisher", "formats":{"Pauper": 0.16}},
        {"name":"Krark-Clan Shaman", "formats":{"Pauper": 0.18}},
        {"name":"Kuldotha Rebirth", "formats":{"Pauper": 0.12}},
        {"name":"Legion Angel", "formats":{"Standard": 0.36}},
        {"name":"Leyline of Sanctity", "formats":{"Modern": 0.10}},
        {"name":"Leyline of the Void", "formats":{"Legacy": 0.14, "Vintage": 0.53}},
        {"name":"Life from the Loam", "formats":{"Legacy": 0.11}},
        {"name":"Lightning Axe", "formats":{"Pioneer": 0.13}},
        {"name":"Lightning Bolt", "formats":{"Modern": 0.35, "Legacy": 0.29, "Vintage": 0.20, "Pauper": 0.33}},
        {"name":"Lion's Eye Diamond", "formats":{"Legacy": 0.11}},
        {"name":"Llanowar Elves", "formats":{"Pioneer": 0.16}},
        {"name":"Lolth, Spider Queen", "formats":{"Standard": 0.33}},
        {"name":"Lotus Petal", "formats":{"Legacy": 0.26}},
        {"name":"Luminarch Aspirant", "formats":{"Standard": 0.38}},
        {"name":"Magus of the Moon", "formats":{"Modern": 0.10}},
        {"name":"Makeshift Munitions", "formats":{"Pauper": 0.29}},
        {"name":"Mana Crypt", "formats":{"Vintage": 0.41}},
        {"name":"Manifold Key", "formats":{"Vintage": 0.29}},
        {"name":"March of Otherworldly Light", "formats":{"Standard": 0.20, "Pioneer": 0.18, "Modern": 0.17}},
        {"name":"Meltdown", "formats":{"Legacy": 0.34}},
        {"name":"Memory Deluge", "formats":{"Pioneer": 0.15}},
        {"name":"Mental Misstep", "formats":{"Vintage": 0.93}},
        {"name":"Merchant Scroll", "formats":{"Vintage": 0.43}},
        {"name":"Mindbreak Trap", "formats":{"Vintage": 0.44}},
        {"name":"Mishra's Bauble", "formats":{"Modern": 0.19, "Legacy": 0.28}},
        {"name":"Mox Emerald", "formats":{"Vintage": 0.66}},
        {"name":"Mox Jet", "formats":{"Vintage": 0.77}},
        {"name":"Mox Opal", "formats":{"Legacy": 0.12}},
        {"name":"Mox Pearl", "formats":{"Vintage": 0.47}},
        {"name":"Mox Ruby", "formats":{"Vintage": 0.62}},
        {"name":"Mox Sapphire", "formats":{"Vintage": 0.80}},
        {"name":"Murktide Regent", "formats":{"Modern": 0.12, "Legacy": 0.26}},
        {"name":"Myr Enforcer", "formats":{"Pauper": 0.12}},
        {"name":"Mystical Dispute", "formats":{"Pioneer": 0.44, "Modern": 0.28}},
        {"name":"Mystical Tutor", "formats":{"Vintage": 0.33}},
        {"name":"Narset, Parter of Veils", "formats":{"Pioneer": 0.26, "Legacy": 0.24, "Vintage": 0.55}},
        {"name":"Narset's Reversal", "formats":{"Pioneer": 0.14}},
        {"name":"Negate", "formats":{"Standard": 0.21}},
        {"name":"Nihil Spellbomb", "formats":{"Pauper": 0.12}},
        {"name":"Ninja of the Deep Hours", "formats":{"Pauper": 0.16}},
        {"name":"Omnath, Locus of Creation", "formats":{"Modern": 0.10}},
        {"name":"Opposition Agent", "formats":{"Vintage": 0.21}},
        {"name":"Opt", "formats":{"Pioneer": 0.14}},
        {"name":"Path to Exile", "formats":{"Modern": 0.13}},
        {"name":"Pithing Needle", "formats":{"Modern": 0.18, "Legacy": 0.23, "Vintage": 0.52}},
        {"name":"Plague Engineer", "formats":{"Legacy": 0.10}},
        {"name":"Play with Fire", "formats":{"Pioneer": 0.12}},
        {"name":"Ponder", "formats":{"Legacy": 0.54, "Vintage": 0.62, "Pauper": 0.12}},
        {"name":"Portable Hole", "formats":{"Standard": 0.28, "Pioneer": 0.23}},
        {"name":"Preordain", "formats":{"Legacy": 0.11, "Vintage": 0.33, "Pauper": 0.25}},
        {"name":"Prismatic Ending", "formats":{"Modern": 0.29, "Legacy": 0.21}},
        {"name":"Prosperous Innkeeper", "formats":{"Pioneer": 0.13}},
        {"name":"Pyroblast", "formats":{"Legacy": 0.50, "Vintage": 0.27, "Pauper": 0.33}},
        {"name":"Ragavan, Nimble Pilferer", "formats":{"Modern": 0.26, "Vintage": 0.24}},
        {"name":"Ray of Enfeeblement", "formats":{"Standard": 0.19}},
        {"name":"Reckoner Bankbuster", "formats":{"Standard": 0.22}},
        {"name":"Reckoner's Bargain", "formats":{"Pauper": 0.12}},
        {"name":"Red Elemental Blast", "formats":{"Legacy": 0.39, "Pauper": 0.25}},
        {"name":"Reidane, God of the Worthy", "formats":{"Standard": 0.25, "Pioneer": 0.12}},
        {"name":"Relic of Progenitus", "formats":{"Modern": 0.33, "Pauper": 0.28}},
        {"name":"Rending Volley", "formats":{"Pioneer": 0.17}},
        {"name":"Rest in Peace", "formats":{"Pioneer": 0.25, "Modern": 0.11}},
        {"name":"Sanctifier en-Vec", "formats":{"Modern": 0.12}},
        {"name":"Seeker of the Way", "formats":{"Pauper": 0.16}},
        {"name":"Sensei's Divining Top", "formats":{"Vintage": 0.34}},
        {"name":"Shadowspear", "formats":{"Modern": 0.10, "Legacy": 0.15}},
        {"name":"Shambling Ghast", "formats":{"Standard": 0.11}},
        {"name":"Shardless Agent", "formats":{"Modern": 0.11}},
        {"name":"Shark Typhoon", "formats":{"Pioneer": 0.14}},
        {"name":"Showdown of the Skalds", "formats":{"Standard": 0.14}},
        {"name":"Skyclave Apparition", "formats":{"Standard": 0.29, "Pioneer": 0.15}},
        {"name":"Snapcaster Mage", "formats":{"Legacy": 0.11}},
        {"name":"Snuff Out", "formats":{"Pauper": 0.1}},
        {"name":"Sol Ring", "formats":{"Vintage": 0.41}},
        {"name":"Solitude", "formats":{"Modern": 0.20}},
        {"name":"Sorin the Mirthless", "formats":{"Standard": 0.28}},
        {"name":"Soul Shatter", "formats":{"Standard": 0.15}},
        {"name":"Soul-Guide Lantern", "formats":{"Modern": 0.12, "Legacy": 0.12, "Vintage": 0.39}},
        {"name":"Spell Pierce", "formats":{"Modern": 0.22, "Pauper": 0.12}},
        {"name":"Spellstutter Sprite", "formats":{"Pauper": 0.17}},
        {"name":"Sphinx of the Steel Wind", "formats":{"Vintage": 0.26}},
        {"name":"Spikefield Hazard", "formats":{"Standard": 0.11}},
        {"name":"Spreading Seas", "formats":{"Modern": 0.10}},
        {"name":"Standard Bearer", "formats":{"Pauper": 0.11}},
        {"name":"Submerge", "formats":{"Legacy": 0.16}},
        {"name":"Subtlety", "formats":{"Modern": 0.10}},
        {"name":"Suffocating Fumes", "formats":{"Pauper": 0.14}},
        {"name":"Supreme Verdict", "formats":{"Pioneer": 0.16, "Modern": 0.11}},
        {"name":"Surgical Extraction", "formats":{"Legacy": 0.56}},
        {"name":"Swords to Plowshares", "formats":{"Legacy": 0.25, "Vintage": 0.23}},
        {"name":"Teferi, Hero of Dominaria", "formats":{"Pioneer": 0.14, "Modern": 0.09}},
        {"name":"Teferi, Time Raveler", "formats":{"Modern": 0.25, "Legacy": 0.13}},
        {"name":"Test of Talents", "formats":{"Standard": 0.19}},
        {"name":"Thalia, Guardian of Thraben", "formats":{"Standard": 0.18}},
        {"name":"The Meathook Massacre", "formats":{"Standard": 0.39}},
        {"name":"The Restoration of Eiganjo", "formats":{"Standard": 0.14}},
        {"name":"The Wandering Emperor", "formats":{"Standard": 0.57, "Pioneer": 0.16}},
        {"name":"Thorn of the Black Rose", "formats":{"Pauper": 0.12}},
        {"name":"Thought Distortion", "formats":{"Pioneer": 0.12}},
        {"name":"Thoughtseize", "formats":{"Pioneer": 0.24, "Modern": 0.19, "Legacy": 0.19}},
        {"name":"Thraben Inspector", "formats":{"Pauper": 0.19}},
        {"name":"Time Vault", "formats":{"Vintage": 0.29}},
        {"name":"Time Walk", "formats":{"Vintage": 0.69}},
        {"name":"Tinker", "formats":{"Vintage": 0.31}},
        {"name":"Tovolar's Huntmaster", "formats":{"Pioneer": 0.11}},
        {"name":"Torpor Orb", "formats":{"Legacy": 0.13}},
        {"name":"Treasure Cruise", "formats":{"Pioneer": 0.12, "Vintage": 0.25}},
        {"name":"Unholy Heat", "formats":{"Modern": 0.21}},
        {"name":"Usher of the Fallen", "formats":{"Standard": 0.13}},
        {"name":"Valorous Stance", "formats":{"Standard": 0.37}},
        {"name":"Vampiric Tutor", "formats":{"Vintage": 0.43}},
        {"name":"Vanishing Verse", "formats":{"Standard": 0.31}},
        {"name":"Veil of Summer", "formats":{"Modern": 0.20}},
        {"name":"Violent Outburst", "formats":{"Modern": 0.10}},
        {"name":"Voice of Resurgence", "formats":{"Pioneer": 0.12}},
        {"name":"Weather the Storm", "formats":{"Pauper": 0.12}},
        {"name":"Wedding Announcement", "formats":{"Standard": 0.37}},
        {"name":"Winota, Joiner of Forces", "formats":{"Standard": 0.11}},
        {"name":"Wrenn and Six", "formats":{"Modern": 0.14}},
        {"name":"Yorion, Sky Nomad", "formats":{"Modern": 0.10}},
    ];
    // @formatter:on
}

function loadRawExtendedBans() {
    // @formatter:off
    return [
        {"name":"Abrade", "formats":{"Standard": 0.08, "Pauper": 0.10}},
        {"name":"Absorb", "formats":{"Pioneer": 0.13}},
        {"name":"Abundant Growth", "formats":{"Modern": 0.08, "Pauper": 0.08}},
        {"name":"Adeline, Resplendent Cathar", "formats":{"Standard": 0.17}},
        {"name":"Aether Gust", "formats":{"Pioneer": 0.23}},
        {"name":"Aether Spellbomb", "formats":{"Legacy": 0.09}},
        {"name":"Allosaurus Shepherd", "formats":{"Legacy": 0.04}},
        {"name":"Alpine Moon", "formats":{"Pioneer": 0.14, "Modern": 0.09}},
        {"name":"Ancestral Recall", "formats":{"Vintage": 0.69}},
        {"name":"Ancient Den", "formats":{"Pauper": 0.14}},
        {"name":"Ancient Tomb", "formats":{"Legacy": 0.20, "Vintage": 0.13}},
        {"name":"Anger of the Gods", "formats":{"Pioneer": 0.13}},
        {"name":"Annul", "formats":{"Pauper": 0.09}},
        {"name":"Ao, the Dawn Sky", "formats":{"Standard": 0.04}},
        {"name":"Approach of the Second Sun", "formats":{"Pioneer": 0.10}},
        {"name":"Arboreal Grazer", "formats":{"Pioneer": 0.11, "Modern": 0.06}},
        {"name":"Arcbound Ravager", "formats":{"Vintage": 0.07}},
        {"name":"Archaeomancer", "formats":{"Pauper": 0.08}},
        {"name":"Archmage's Charm", "formats":{"Modern": 0.19}},
        {"name":"Archon of Emeria", "formats":{"Standard": 0.19, "Pioneer": 0.09}},
        {"name":"Arclight Phoenix", "formats":{"Pioneer": 0.11}},
        {"name":"Arctic Treeline", "formats":{"Pauper": 0.04}},
        {"name":"Arid Mesa", "formats":{"Modern": 0.15}},
        {"name":"Ash Barrens", "formats":{"Pauper": 0.31}},
        {"name":"Augur of Bolas", "formats":{"Pauper": 0.13}},
        {"name":"Azorius Chancery", "formats":{"Pauper": 0.05}},
        {"name":"Azusa, Lost but Seeking", "formats":{"Modern": 0.05}},
        {"name":"Badlands", "formats":{"Legacy": 0.12, "Vintage": 0.08}},
        {"name":"Bala Ged Recovery", "formats":{"Pioneer": 0.10}},
        {"name":"Baleful Strix", "formats":{"Legacy": 0.08}},
        {"name":"Barkchannel Pathway", "formats":{"Standard": 0.03}},
        {"name":"Barren Moor", "formats":{"Pauper": 0.04}},
        {"name":"Basking Rootwalla", "formats":{"Vintage": 0.12}},
        {"name":"Bayou", "formats":{"Legacy": 0.12, "Vintage": 0.13}},
        {"name":"Bazaar of Baghdad", "formats":{"Vintage": 0.19}},
        {"name":"Behold the Multiverse", "formats":{"Standard": 0.11}},
        {"name":"Birchlore Rangers", "formats":{"Legacy": 0.04}},
        {"name":"Black Lotus", "formats":{"Vintage": 0.83}},
        {"name":"Blade Historian", "formats":{"Pioneer": 0.07}},
        {"name":"Blast Zone", "formats":{"Modern": 0.07, "Legacy": 0.06}},
        {"name":"Blazing Rootwalla", "formats":{"Vintage": 0.03}},
        {"name":"Blightsteel Colossus", "formats":{"Vintage": 0.08}},
        {"name":"Blightstep Pathway", "formats":{"Standard": 0.12, "Pioneer": 0.15}},
        {"name":"Blood Baron of Vizkopa", "formats":{"Pioneer": 0.04}},
        {"name":"Blood Crypt", "formats":{"Pioneer": 0.17, "Modern": 0.12}},
        {"name":"Blood Fountain", "formats":{"Pauper": 0.12}},
        {"name":"Blood Moon", "formats":{"Modern": 0.19, "Legacy": 0.10}},
        {"name":"Bloodchief's Thirst", "formats":{"Standard": 0.17}},
        {"name":"Bloodfell Caves", "formats":{"Pauper": 0.03}},
        {"name":"Bloodghast", "formats":{"Vintage": 0.10}},
        {"name":"Bloodstained Mire", "formats":{"Modern": 0.15, "Legacy": 0.13, "Vintage": 0.02}},
        {"name":"Bloodtithe Harvester", "formats":{"Standard": 0.06, "Pioneer": 0.11}},
        {"name":"Blue Elemental Blast", "formats":{"Pauper": 0.25}},
        {"name":"Bojuka Bog", "formats":{"Legacy": 0.13, "Pauper": 0.06}},
        {"name":"Bolas's Citadel", "formats":{"Vintage": 0.29}},
        {"name":"Bonecrusher Giant", "formats":{"Pioneer": 0.16, "Modern": 0.06}},
        {"name":"Boros Garrison", "formats":{"Pauper": 0.17}},
        {"name":"Boseiju, Who Endures", "formats":{"Standard": 0.21, "Pioneer": 0.18, "Modern": 0.33, "Legacy": 0.21, "Vintage": 0.17}},
        {"name":"Botanical Sanctum", "formats":{"Pioneer": 0.16}},
        {"name":"Brainstorm", "formats":{"Legacy": 0.55, "Vintage": 0.67, "Pauper": 0.14}},
        {"name":"Branchloft Pathway", "formats":{"Standard": 0.19, "Pioneer": 0.17}},
        {"name":"Brazen Borrower", "formats":{"Pioneer": 0.07, "Modern": 0.12, "Legacy": 0.29, "Vintage": 0.07}},
        {"name":"Breeding Pool", "formats":{"Pioneer": 0.13, "Modern": 0.29}},
        {"name":"Brightclimb Pathway", "formats":{"Standard": 0.32}},
        {"name":"Brutal Cathar", "formats":{"Standard": 0.23, "Pioneer": 0.13}},
        {"name":"Carpet of Flowers", "formats":{"Legacy": 0.13}},
        {"name":"Cast Down", "formats":{"Pauper": 0.16}},
        {"name":"Castle Ardenvale", "formats":{"Pioneer": 0.14}},
        {"name":"Castle Garenbrig", "formats":{"Modern": 0.06}},
        {"name":"Castle Locthwain", "formats":{"Pioneer": 0.10}},
        {"name":"Castle Vantress", "formats":{"Pioneer": 0.13, "Modern": 0.08}},
        {"name":"Cauldron Familiar", "formats":{"Pioneer": 0.07}},
        {"name":"Cave of Temptation", "formats":{"Pauper": 0.08}},
        {"name":"Cave of the Frost Dragon", "formats":{"Standard": 0.36}},
        {"name":"Cavern of Souls", "formats":{"Modern": 0.13, "Legacy": 0.10, "Vintage": 0.01}},
        {"name":"Celestial Colonnade", "formats":{"Modern": 0.06}},
        {"name":"Censor", "formats":{"Pioneer": 0.11}},
        {"name":"Chain Lightning", "formats":{"Legacy": 0.13}},
        {"name":"Chainer's Edict", "formats":{"Pauper": 0.23}},
        {"name":"Chalice of the Void", "formats":{"Modern": 0.18, "Legacy": 0.12, "Vintage": 0.21}},
        {"name":"Chandra, Torch of Defiance", "formats":{"Pioneer": 0.15}},
        {"name":"Chart a Course", "formats":{"Pioneer": 0.11}},
        {"name":"Check for Traps", "formats":{"Standard": 0.15}},
        {"name":"Choke", "formats":{"Legacy": 0.08}},
        {"name":"Chromatic Star", "formats":{"Pauper": 0.20}},
        {"name":"Cinderclasm", "formats":{"Standard": 0.11}},
        {"name":"Circle of Confinement", "formats":{"Standard": 0.14}},
        {"name":"City of Traitors", "formats":{"Legacy": 0.08, "Vintage": 0.01}},
        {"name":"Clearwater Pathway", "formats":{"Standard": 0.13}},
        {"name":"Collector Ouphe", "formats":{"Legacy": 0.12, "Vintage": 0.19}},
        {"name":"Concealing Curtains", "formats":{"Standard": 0.06}},
        {"name":"Consider", "formats":{"Pioneer": 0.14, "Modern": 0.13}},
        {"name":"Containment Priest", "formats":{"Legacy": 0.09}},
        {"name":"Counterspell", "formats":{"Modern": 0.26, "Pauper": 0.26}},
        {"name":"Court of Cunning", "formats":{"Legacy": 0.10}},
        {"name":"Crackling Drake", "formats":{"Pioneer": 0.07}},
        {"name":"Cragcrown Pathway", "formats":{"Standard": 0.14, "Pioneer": 0.13}},
        {"name":"Craterhoof Behemoth", "formats":{"Legacy": 0.04}},
        {"name":"Crawling Barrens", "formats":{"Standard": 0.11}},
        {"name":"Crimson Acolyte", "formats":{"Pauper": 0.07}},
        {"name":"Crimson Fleet Commodore", "formats":{"Pauper": 0.05}},
        {"name":"Crop Rotation", "formats":{"Legacy": 0.11}},
        {"name":"Crumbling Vestige", "formats":{"Pauper": 0.03}},
        {"name":"Cultivator Colossus", "formats":{"Modern": 0.05}},
        {"name":"Curator of Mysteries", "formats":{"Modern": 0.04}},
        {"name":"Dack Fayden", "formats":{"Vintage": 0.24}},
        {"name":"Damping Sphere", "formats":{"Pioneer": 0.15, "Modern": 0.07}},
        {"name":"Dark Depths", "formats":{"Legacy": 0.09}},
        {"name":"Dark Ritual", "formats":{"Legacy": 0.10}},
        {"name":"Darkbore Pathway", "formats":{"Standard": 0.04}},
        {"name":"Darksteel Citadel", "formats":{"Pauper": 0.02}},
        {"name":"Dawnbringer Cleric", "formats":{"Standard": 0.03, "Pauper": 0.08}},
        {"name":"Day's Undoing", "formats":{"Legacy": 0.09}},
        {"name":"Daze", "formats":{"Legacy": 0.30}},
        {"name":"Dead // Gone", "formats":{"Modern": 0.07}},
        {"name":"Deadly Dispute", "formats":{"Standard": 0.15, "Pauper": 0.21}},
        {"name":"Deafening Silence", "formats":{"Pioneer": 0.15}},
        {"name":"Death's Shadow", "formats":{"Modern": 0.04}},
        {"name":"Deathcap Glade", "formats":{"Standard": 0.03}},
        {"name":"Deathrite Shaman", "formats":{"Vintage": 0.23}},
        {"name":"Delver of Secrets", "formats":{"Legacy": 0.23}},
        {"name":"Demonic Tutor", "formats":{"Vintage": 0.50}},
        {"name":"Den of the Bugbear", "formats":{"Standard": 0.15, "Pioneer": 0.21}},
        {"name":"Deserted Beach", "formats":{"Standard": 0.20, "Pioneer": 0.13}},
        {"name":"Dig Through Time", "formats":{"Vintage": 0.53}},
        {"name":"Disdainful Stroke", "formats":{"Standard": 0.26}},
        {"name":"Dismember", "formats":{"Modern": 0.09, "Legacy": 0.09}},
        {"name":"Dispel", "formats":{"Pauper": 0.24}},
        {"name":"Doomskar", "formats":{"Standard": 0.20}},
        {"name":"Dovin's Veto", "formats":{"Pioneer": 0.18, "Modern": 0.11}},
        {"name":"Dragon's Fire", "formats":{"Standard": 0.09}},
        {"name":"Dragon's Rage Channeler", "formats":{"Modern": 0.18, "Legacy": 0.23}},
        {"name":"Dreadbore", "formats":{"Pioneer": 0.12}},
        {"name":"Dreadhorde Arcanist", "formats":{"Vintage": 0.05}},
        {"name":"Dream Trawler", "formats":{"Pioneer": 0.07}},
        {"name":"Dreamroot Cascade", "formats":{"Standard": 0.01}},
        {"name":"Dress Down", "formats":{"Modern": 0.22, "Legacy": 0.10}},
        {"name":"Drossforge Bridge", "formats":{"Pauper": 0.21}},
        {"name":"Dryad Arbor", "formats":{"Legacy": 0.10, "Vintage": 0.09}},
        {"name":"Dryad of the Ilysian Grove", "formats":{"Modern": 0.07}},
        {"name":"Duress", "formats":{"Standard": 0.34, "Pioneer": 0.13, "Pauper": 0.27}},
        {"name":"Dust to Dust", "formats":{"Pauper": 0.23}},
        {"name":"Echoing Decay", "formats":{"Pauper": 0.09}},
        {"name":"Echoing Truth", "formats":{"Pauper": 0.16}},
        {"name":"Edgar, Charmed Groom", "formats":{"Standard": 0.09}},
        {"name":"Eidolon of Rhetoric", "formats":{"Pioneer": 0.06}},
        {"name":"Eidolon of the Great Revel", "formats":{"Pioneer": 0.09, "Modern": 0.04}},
        {"name":"Eiganjo, Seat of the Empire", "formats":{"Standard": 0.64, "Pioneer": 0.16}},
        {"name":"Electrickery", "formats":{"Pauper": 0.24}},
        {"name":"Elite Spellbinder", "formats":{"Standard": 0.25, "Pioneer": 0.13}},
        {"name":"Elvish Mystic", "formats":{"Pioneer": 0.16}},
        {"name":"Elvish Reclaimer", "formats":{"Legacy": 0.10}},
        {"name":"Elvish Visionary", "formats":{"Legacy": 0.04}},
        {"name":"Emeria's Call", "formats":{"Standard": 0.29}},
        {"name":"Emrakul, the Aeons Torn", "formats":{"Modern": 0.08, "Legacy": 0.08}},
        {"name":"Emrakul, the Promised End", "formats":{"Modern": 0.07}},
        {"name":"Emry, Lurker of the Loch", "formats":{"Legacy": 0.08}},
        {"name":"End the Festivities", "formats":{"Legacy": 0.17}},
        {"name":"Endurance", "formats":{"Modern": 0.29, "Legacy": 0.23, "Vintage": 0.11}},
        {"name":"Energy Flux", "formats":{"Vintage": 0.17}},
        {"name":"Engineered Explosives", "formats":{"Modern": 0.35}},
        {"name":"Ensnaring Bridge", "formats":{"Modern": 0.08}},
        {"name":"Environmental Sciences", "formats":{"Standard": 0.11}},
        {"name":"Ephemerate", "formats":{"Modern": 0.08, "Pauper": 0.09}},
        {"name":"Esika's Chariot", "formats":{"Standard": 0.13, "Pioneer": 0.13}},
        {"name":"Esper Sentinel", "formats":{"Modern": 0.07}},
        {"name":"Ethereal Armor", "formats":{"Pauper": 0.09}},
        {"name":"Ethersworn Canonist", "formats":{"Legacy": 0.05}},
        {"name":"Evolving Wilds", "formats":{"Pauper": 0.13}},
        {"name":"Expedition Map", "formats":{"Modern": 0.10, "Legacy": 0.08}},
        {"name":"Experimental Synthesizer", "formats":{"Pauper": 0.27}},
        {"name":"Expressive Iteration", "formats":{"Standard": 0.11, "Pioneer": 0.18, "Modern": 0.24, "Legacy": 0.26}},
        {"name":"Eyetwitch", "formats":{"Standard": 0.08}},
        {"name":"Fable of the Mirror-Breaker", "formats":{"Pioneer": 0.12}},
        {"name":"Fading Hope", "formats":{"Standard": 0.13}},
        {"name":"Fae of Wishes", "formats":{"Pioneer": 0.10}},
        {"name":"Faerie Macabre", "formats":{"Legacy": 0.12}},
        {"name":"Faerie Miscreant", "formats":{"Pauper": 0.06}},
        {"name":"Faerie Seer", "formats":{"Pauper": 0.16}},
        {"name":"Faithless Looting", "formats":{"Pauper": 0.12}},
        {"name":"Farewell", "formats":{"Standard": 0.27, "Pioneer": 0.14}},
        {"name":"Fatal Push", "formats":{"Pioneer": 0.24, "Modern": 0.11, "Vintage": 0.19}},
        {"name":"Fateful Absence", "formats":{"Standard": 0.13, "Pioneer": 0.10}},
        {"name":"Field of Ruin", "formats":{"Standard": 0.16, "Pioneer": 0.14}},
        {"name":"Field of the Dead", "formats":{"Legacy": 0.06}},
        {"name":"Fiery Cannonade", "formats":{"Pauper": 0.25}},
        {"name":"Fiery Impulse", "formats":{"Pioneer": 0.13}},
        {"name":"Fiery Islet", "formats":{"Modern": 0.13}},
        {"name":"Fire // Ice", "formats":{"Modern": 0.10}},
        {"name":"Firebrand Archer", "formats":{"Pauper": 0.04}},
        {"name":"Flame-Blessed Bolt", "formats":{"Pioneer": 0.11}},
        {"name":"Flamewave Invoker", "formats":{"Pauper": 0.04}},
        {"name":"Flaring Pain", "formats":{"Pauper": 0.13}},
        {"name":"Flickerwisp", "formats":{"Legacy": 0.04}},
        {"name":"Flooded Strand", "formats":{"Modern": 0.33, "Legacy": 0.41, "Vintage": 0.48}},
        {"name":"Flusterstorm", "formats":{"Legacy": 0.32, "Vintage": 0.67}},
        {"name":"Forbidden Orchard", "formats":{"Vintage": 0.02}},
        {"name":"Force of Negation", "formats":{"Modern": 0.24, "Legacy": 0.52, "Vintage": 0.63}},
        {"name":"Force of Vigor", "formats":{"Modern": 0.31, "Legacy": 0.17, "Vintage": 0.32}},
        {"name":"Force of Will", "formats":{"Legacy": 0.61, "Vintage": 0.78}},
        {"name":"Forgotten Cave", "formats":{"Pauper": 0.07}},
        {"name":"Foundation Breaker", "formats":{"Modern": 0.06}},
        {"name":"Foundry Inspector", "formats":{"Vintage": 0.08}},
        {"name":"Frogmite", "formats":{"Pauper": 0.11}},
        {"name":"Fury", "formats":{"Modern": 0.30, "Vintage": 0.05}},
        {"name":"Furycalm Snarl", "formats":{"Standard": 0.03}},
        {"name":"Gaea's Cradle", "formats":{"Legacy": 0.06, "Vintage": 0.03}},
        {"name":"Galvanic Blast", "formats":{"Pauper": 0.33}},
        {"name":"Galvanic Iteration", "formats":{"Pioneer": 0.15}},
        {"name":"Gemstone Caverns", "formats":{"Modern": 0.07}},
        {"name":"Generous Visitor", "formats":{"Standard": 0.07}},
        {"name":"Ghost Quarter", "formats":{"Vintage": 0.03}},
        {"name":"Gilded Goose", "formats":{"Pioneer": 0.06}},
        {"name":"Gingerbrute", "formats":{"Vintage": 0.07}},
        {"name":"Gitaxian Probe", "formats":{"Vintage": 0.69}},
        {"name":"Glacial Chasm", "formats":{"Legacy": 0.05}},
        {"name":"Glacial Fortress", "formats":{"Pioneer": 0.12}},
        {"name":"Gladecover Scout", "formats":{"Pauper": 0.08}},
        {"name":"Glint Hawk", "formats":{"Pauper": 0.15}},
        {"name":"Go Blank", "formats":{"Standard": 0.26, "Pioneer": 0.16}},
        {"name":"Goblin Guide", "formats":{"Modern": 0.04}},
        {"name":"Goblin Matron", "formats":{"Pauper": 0.05}},
        {"name":"God-Pharaoh's Faithful", "formats":{"Pauper": 0.04}},
        {"name":"Golden Egg", "formats":{"Pauper": 0.11}},
        {"name":"Goldspan Dragon", "formats":{"Standard": 0.14}},
        {"name":"Golgari Grave-Troll", "formats":{"Vintage": 0.07}},
        {"name":"Golgari Thug", "formats":{"Vintage": 0.07}},
        {"name":"Gorilla Shaman", "formats":{"Pauper": 0.29}},
        {"name":"Grafdigger's Cage", "formats":{"Legacy": 0.27, "Vintage": 0.31}},
        {"name":"Graveyard Trespasser", "formats":{"Standard": 0.11, "Pioneer": 0.10}},
        {"name":"Great Furnace", "formats":{"Pauper": 0.32}},
        {"name":"Green Sun's Zenith", "formats":{"Legacy": 0.12}},
        {"name":"Grief", "formats":{"Modern": 0.06, "Vintage": 0.09}},
        {"name":"Griselbrand", "formats":{"Legacy": 0.07}},
        {"name":"Grove of the Burnwillows", "formats":{"Legacy": 0.05}},
        {"name":"Guardian of Faith", "formats":{"Standard": 0.19}},
        {"name":"Guardian of the Guildpact", "formats":{"Pauper": 0.04}},
        {"name":"Gurmag Angler", "formats":{"Pauper": 0.19}},
        {"name":"Gush", "formats":{"Vintage": 0.23}},
        {"name":"Gut Shot", "formats":{"Pauper": 0.16}},
        {"name":"Hagra Mauling", "formats":{"Standard": 0.15}},
        {"name":"Halana and Alena, Partners", "formats":{"Standard": 0.04}},
        {"name":"Hall of Storm Giants", "formats":{"Standard": 0.19, "Pioneer": 0.26, "Modern": 0.06}},
        {"name":"Hallowed Fountain", "formats":{"Pioneer": 0.22, "Modern": 0.25}},
        {"name":"Haunted Ridge", "formats":{"Standard": 0.10, "Pioneer": 0.13}},
        {"name":"Heliod's Pilgrim", "formats":{"Pauper": 0.05}},
        {"name":"Hengegate Pathway", "formats":{"Standard": 0.22, "Pioneer": 0.16}},
        {"name":"Henrika Domnathi", "formats":{"Standard": 0.09}},
        {"name":"Heritage Druid", "formats":{"Legacy": 0.04}},
        {"name":"Hidden Strings", "formats":{"Pioneer": 0.10}},
        {"name":"Hive of the Eye Tyrant", "formats":{"Standard": 0.39, "Pioneer": 0.17}},
        {"name":"Hogaak, Arisen Necropolis", "formats":{"Vintage": 0.10}},
        {"name":"Hollow One", "formats":{"Vintage": 0.19}},
        {"name":"Hopeful Initiate", "formats":{"Standard": 0.17}},
        {"name":"Hullbreacher", "formats":{"Legacy": 0.18, "Vintage": 0.23}},
        {"name":"Hullbreaker Horror", "formats":{"Standard": 0.10, "Pioneer": 0.16}},
        {"name":"Hurkyl's Recall", "formats":{"Vintage": 0.31}},
        {"name":"Hydroblast", "formats":{"Pauper": 0.17}},
        {"name":"Ice Tunnel", "formats":{"Pauper": 0.09}},
        {"name":"Ice-Fang Coatl", "formats":{"Modern": 0.06}},
        {"name":"Ichor Wellspring", "formats":{"Pauper": 0.32}},
        {"name":"Ichorid", "formats":{"Vintage": 0.07}},
        {"name":"Ignoble Hierarch", "formats":{"Modern": 0.05}},
        {"name":"Infernal Grasp", "formats":{"Standard": 0.22}},
        {"name":"Inkmoth Nexus", "formats":{"Modern": 0.06}},
        {"name":"Inquisition of Kozilek", "formats":{"Modern": 0.09}},
        {"name":"Inspiring Vantage", "formats":{"Pioneer": 0.07, "Modern": 0.07}},
        {"name":"Intrepid Adversary", "formats":{"Standard": 0.16}},
        {"name":"Inventors' Fair", "formats":{"Vintage": 0.01}},
        {"name":"Irrigated Farmland", "formats":{"Pioneer": 0.13}},
        {"name":"Iymrith, Desert Doom", "formats":{"Standard": 0.05}},
        {"name":"Izzet Staticaster", "formats":{"Legacy": 0.04}},
        {"name":"Jace, the Mind Sculptor", "formats":{"Modern": 0.18, "Legacy": 0.11}},
        {"name":"Jegantha, the Wellspring", "formats":{"Pioneer": 0.05}},
        {"name":"Journey to Nowhere", "formats":{"Pauper": 0.10}},
        {"name":"Jukai Naturalist", "formats":{"Standard": 0.07}},
        {"name":"Jwari Disruption", "formats":{"Standard": 0.17}},
        {"name":"Kabira Crossroads", "formats":{"Pauper": 0.02}},
        {"name":"Kaito Shizuki", "formats":{"Standard": 0.11}},
        {"name":"Kalitas, Traitor of Ghet", "formats":{"Pioneer": 0.10}},
        {"name":"Kambal, Consul of Allocation", "formats":{"Pioneer": 0.05}},
        {"name":"Kami of Transience", "formats":{"Standard": 0.07}},
        {"name":"Kappa Cannoneer", "formats":{"Legacy": 0.08}},
        {"name":"Karakas", "formats":{"Legacy": 0.30, "Vintage": 0.02}},
        {"name":"Katilda, Dawnhart Martyr", "formats":{"Standard": 0.03}},
        {"name":"Kenrith, the Returned King", "formats":{"Pioneer": 0.10}},
        {"name":"Ketria Triome", "formats":{"Modern": 0.17}},
        {"name":"Khalni Garden", "formats":{"Pauper": 0.01}},
        {"name":"Kitchen Imp", "formats":{"Pauper": 0.04}},
        {"name":"Knight of the Reliquary", "formats":{"Legacy": 0.04}},
        {"name":"Kolaghan's Command", "formats":{"Pioneer": 0.12}},
        {"name":"Kor Skyfisher", "formats":{"Pauper": 0.16}},
        {"name":"Krark-Clan Shaman", "formats":{"Pauper": 0.18}},
        {"name":"Kroxa, Titan of Death's Hunger", "formats":{"Pioneer": 0.08, "Modern": 0.06}},
        {"name":"Kuldotha Rebirth", "formats":{"Pauper": 0.12}},
        {"name":"Laelia, the Blade Reforged", "formats":{"Vintage": 0.05}},
        {"name":"Lair of the Hydra", "formats":{"Standard": 0.19, "Pioneer": 0.07}},
        {"name":"Lavinia, Azorius Renegade", "formats":{"Vintage": 0.17}},
        {"name":"Leave No Trace", "formats":{"Pauper": 0.10}},
        {"name":"Legion Angel", "formats":{"Standard": 0.36}},
        {"name":"Leovold, Emissary of Trest", "formats":{"Vintage": 0.05}},
        {"name":"Leyline of Sanctity", "formats":{"Modern": 0.10}},
        {"name":"Leyline of the Void", "formats":{"Legacy": 0.14, "Vintage": 0.53}},
        {"name":"Library of Alexandria", "formats":{"Vintage": 0.00}},
        {"name":"Lier, Disciple of the Drowned", "formats":{"Standard": 0.11, "Pioneer": 0.05}},
        {"name":"Life from the Loam", "formats":{"Legacy": 0.11}},
        {"name":"Lightning Axe", "formats":{"Pioneer": 0.13}},
        {"name":"Lightning Bolt", "formats":{"Modern": 0.35, "Legacy": 0.29, "Vintage": 0.20, "Pauper": 0.33}},
        {"name":"Lion Sash", "formats":{"Legacy": 0.05}},
        {"name":"Lion's Eye Diamond", "formats":{"Legacy": 0.11}},
        {"name":"Llanowar Elves", "formats":{"Pioneer": 0.16}},
        {"name":"Lodestone Golem", "formats":{"Vintage": 0.10}},
        {"name":"Lolth, Spider Queen", "formats":{"Standard": 0.33}},
        {"name":"Lone Missionary", "formats":{"Pauper": 0.09}},
        {"name":"Lorehold Campus", "formats":{"Pauper": 0.06}},
        {"name":"Lotus Field", "formats":{"Pioneer": 0.10}},
        {"name":"Lotus Petal", "formats":{"Legacy": 0.26}},
        {"name":"Luminarch Aspirant", "formats":{"Standard": 0.38}},
        {"name":"Magus of the Moon", "formats":{"Modern": 0.10, "Legacy": 0.07}},
        {"name":"Makeshift Munitions", "formats":{"Pauper": 0.29}},
        {"name":"Malevolent Hermit", "formats":{"Standard": 0.11, "Legacy": 0.05}},
        {"name":"Mana Confluence", "formats":{"Pioneer": 0.17}},
        {"name":"Mana Crypt", "formats":{"Vintage": 0.41}},
        {"name":"Mana Vault", "formats":{"Vintage": 0.20}},
        {"name":"Manifold Key", "formats":{"Vintage": 0.29}},
        {"name":"March of Otherworldly Light", "formats":{"Standard": 0.20, "Pioneer": 0.18, "Modern": 0.17}},
        {"name":"Marsh Flats", "formats":{"Modern": 0.08}},
        {"name":"Mascot Exhibition", "formats":{"Standard": 0.11}},
        {"name":"Masked Vandal", "formats":{"Pauper": 0.05}},
        {"name":"Master of Death", "formats":{"Vintage": 0.03}},
        {"name":"Mausoleum Wanderer", "formats":{"Pioneer": 0.05}},
        {"name":"Mayhem Devil", "formats":{"Pioneer": 0.07}},
        {"name":"Maze of Ith", "formats":{"Legacy": 0.08}},
        {"name":"Meddling Mage", "formats":{"Modern": 0.04}},
        {"name":"Meltdown", "formats":{"Legacy": 0.34}},
        {"name":"Memnite", "formats":{"Modern": 0.06}},
        {"name":"Memory Deluge", "formats":{"Standard": 0.11, "Pioneer": 0.15, "Modern": 0.09}},
        {"name":"Mental Misstep", "formats":{"Vintage": 0.93}},
        {"name":"Merchant Scroll", "formats":{"Vintage": 0.43}},
        {"name":"Mindbreak Trap", "formats":{"Vintage": 0.44}},
        {"name":"Mishra's Bauble", "formats":{"Modern": 0.19, "Legacy": 0.28}},
        {"name":"Mishra's Workshop", "formats":{"Vintage": 0.11}},
        {"name":"Mistvault Bridge", "formats":{"Pauper": 0.11}},
        {"name":"Misty Rainforest", "formats":{"Modern": 0.42, "Legacy": 0.44, "Vintage": 0.63}},
        {"name":"Monastery Mentor", "formats":{"Legacy": 0.04, "Vintage": 0.19}},
        {"name":"Monastery Swiftspear", "formats":{"Pioneer": 0.11, "Modern": 0.06}},
        {"name":"Moon-Circuit Hacker", "formats":{"Pauper": 0.10}},
        {"name":"Mortuary Mire", "formats":{"Pauper": 0.06}},
        {"name":"Mother of Runes", "formats":{"Legacy": 0.05}},
        {"name":"Mox Emerald", "formats":{"Vintage": 0.66}},
        {"name":"Mox Jet", "formats":{"Vintage": 0.77}},
        {"name":"Mox Opal", "formats":{"Legacy": 0.12}},
        {"name":"Mox Pearl", "formats":{"Vintage": 0.47}},
        {"name":"Mox Ruby", "formats":{"Vintage": 0.62}},
        {"name":"Mox Sapphire", "formats":{"Vintage": 0.80}},
        {"name":"Mulldrifter", "formats":{"Pauper": 0.10}},
        {"name":"Murktide Regent", "formats":{"Modern": 0.12, "Legacy": 0.26, "Vintage": 0.07}},
        {"name":"Mutagenic Growth", "formats":{"Pauper": 0.08}},
        {"name":"Mutavault", "formats":{"Pioneer": 0.07}},
        {"name":"Myr Enforcer", "formats":{"Pauper": 0.12}},
        {"name":"Myr Retriever", "formats":{"Pauper": 0.05}},
        {"name":"Mystic Gate", "formats":{"Modern": 0.07}},
        {"name":"Mystic Sanctuary", "formats":{"Legacy": 0.20, "Vintage": 0.11}},
        {"name":"Mystical Dispute", "formats":{"Pioneer": 0.44, "Modern": 0.28}},
        {"name":"Mystical Tutor", "formats":{"Vintage": 0.33}},
        {"name":"Narcomoeba", "formats":{"Vintage": 0.07}},
        {"name":"Narset, Parter of Veils", "formats":{"Pioneer": 0.26, "Legacy": 0.24, "Vintage": 0.55}},
        {"name":"Narset's Reversal", "formats":{"Pioneer": 0.14}},
        {"name":"Necroblossom Snarl", "formats":{"Standard": 0.01}},
        {"name":"Needleverge Pathway", "formats":{"Standard": 0.25, "Pioneer": 0.11}},
        {"name":"Negate", "formats":{"Standard": 0.21}},
        {"name":"Nihil Spellbomb", "formats":{"Pauper": 0.12}},
        {"name":"Ninja of the Deep Hours", "formats":{"Pauper": 0.16}},
        {"name":"Nurturing Peatland", "formats":{"Modern": 0.06}},
        {"name":"Oboro, Palace in the Clouds", "formats":{"Vintage": 0.00}},
        {"name":"Okiba-Gang Shinobi", "formats":{"Pauper": 0.04}},
        {"name":"Oko, Thief of Crowns", "formats":{"Vintage": 0.15}},
        {"name":"Omnath, Locus of Creation", "formats":{"Pioneer": 0.04, "Modern": 0.10}},
        {"name":"Omniscience", "formats":{"Pioneer": 0.10}},
        {"name":"Once Upon a Time", "formats":{"Vintage": 0.08}},
        {"name":"Opposition Agent", "formats":{"Vintage": 0.21}},
        {"name":"Opt", "formats":{"Pioneer": 0.14}},
        {"name":"Ornithopter", "formats":{"Modern": 0.05}},
        {"name":"Otawara, Soaring City", "formats":{"Standard": 0.17, "Pioneer": 0.38, "Modern": 0.30, "Legacy": 0.13, "Vintage": 0.02}},
        {"name":"Outland Liberator", "formats":{"Standard": 0.06, "Modern": 0.04}},
        {"name":"Overgrown Farmland", "formats":{"Standard": 0.17}},
        {"name":"Overgrown Tomb", "formats":{"Pioneer": 0.07, "Modern": 0.09}},
        {"name":"Palace Sentinels", "formats":{"Pauper": 0.05}},
        {"name":"Path to Exile", "formats":{"Modern": 0.13}},
        {"name":"Peacekeeper", "formats":{"Legacy": 0.04}},
        {"name":"Petrified Field", "formats":{"Vintage": 0.02}},
        {"name":"Phyrexian Revoker", "formats":{"Vintage": 0.09}},
        {"name":"Pieces of the Puzzle", "formats":{"Pioneer": 0.10}},
        {"name":"Pithing Needle", "formats":{"Modern": 0.18, "Legacy": 0.23, "Vintage": 0.52}},
        {"name":"Plague Engineer", "formats":{"Legacy": 0.10}},
        {"name":"Play with Fire", "formats":{"Pioneer": 0.12}},
        {"name":"Polluted Delta", "formats":{"Modern": 0.21, "Legacy": 0.41, "Vintage": 0.56}},
        {"name":"Ponder", "formats":{"Legacy": 0.54, "Vintage": 0.62, "Pauper": 0.12}},
        {"name":"Pore Over the Pages", "formats":{"Pioneer": 0.10}},
        {"name":"Portable Hole", "formats":{"Standard": 0.28, "Pioneer": 0.23}},
        {"name":"Power Word Kill", "formats":{"Standard": 0.09}},
        {"name":"Preordain", "formats":{"Legacy": 0.11, "Vintage": 0.33, "Pauper": 0.25}},
        {"name":"Primeval Titan", "formats":{"Modern": 0.06}},
        {"name":"Prismari Command", "formats":{"Standard": 0.10, "Modern": 0.08}},
        {"name":"Prismatic Ending", "formats":{"Modern": 0.29, "Legacy": 0.21, "Vintage": 0.15}},
        {"name":"Prismatic Vista", "formats":{"Legacy": 0.12, "Vintage": 0.02}},
        {"name":"Prized Amalgam", "formats":{"Vintage": 0.07}},
        {"name":"Professor of Symbology", "formats":{"Standard": 0.06}},
        {"name":"Progenitus", "formats":{"Legacy": 0.04}},
        {"name":"Prosperous Innkeeper", "formats":{"Standard": 0.10, "Pioneer": 0.13}},
        {"name":"Puresteel Paladin", "formats":{"Modern": 0.04}},
        {"name":"Putrid Goblin", "formats":{"Pauper": 0.04}},
        {"name":"Pyroblast", "formats":{"Legacy": 0.50, "Vintage": 0.27, "Pauper": 0.33}},
        {"name":"Quirion Ranger", "formats":{"Pauper": 0.05}},
        {"name":"Rabbit Battery", "formats":{"Standard": 0.04}},
        {"name":"Radiant Fountain", "formats":{"Pauper": 0.07}},
        {"name":"Ragavan, Nimble Pilferer", "formats":{"Modern": 0.26, "Vintage": 0.24}},
        {"name":"Rakdos Carnarium", "formats":{"Pauper": 0.10}},
        {"name":"Rally the Peasants", "formats":{"Pauper": 0.10}},
        {"name":"Rampaging Ferocidon", "formats":{"Pioneer": 0.04}},
        {"name":"Ramunap Excavator", "formats":{"Legacy": 0.07}},
        {"name":"Ramunap Ruins", "formats":{"Pioneer": 0.09}},
        {"name":"Rancor", "formats":{"Pauper": 0.10}},
        {"name":"Rattlechains", "formats":{"Pioneer": 0.05}},
        {"name":"Raugrin Triome", "formats":{"Pioneer": 0.08, "Modern": 0.20}},
        {"name":"Ravenous Trap", "formats":{"Vintage": 0.20}},
        {"name":"Ray of Enfeeblement", "formats":{"Standard": 0.19}},
        {"name":"Razortide Bridge", "formats":{"Pauper": 0.03}},
        {"name":"Reckless Stormseeker", "formats":{"Standard": 0.05}},
        {"name":"Reckoner Bankbuster", "formats":{"Standard": 0.22}},
        {"name":"Reckoner's Bargain", "formats":{"Pauper": 0.12}},
        {"name":"Recruiter of the Guard", "formats":{"Legacy": 0.05}},
        {"name":"Red Elemental Blast", "formats":{"Legacy": 0.39, "Pauper": 0.25}},
        {"name":"Reidane, God of the Worthy", "formats":{"Standard": 0.25, "Pioneer": 0.12}},
        {"name":"Relic of Progenitus", "formats":{"Modern": 0.33, "Pauper": 0.28}},
        {"name":"Rending Volley", "formats":{"Pioneer": 0.17}},
        {"name":"Rest in Peace", "formats":{"Pioneer": 0.25, "Modern": 0.11}},
        {"name":"Revoke Existence", "formats":{"Pauper": 0.09}},
        {"name":"Riftstone Portal", "formats":{"Vintage": 0.00}},
        {"name":"Rishadan Port", "formats":{"Legacy": 0.08}},
        {"name":"Rite of Oblivion", "formats":{"Standard": 0.10}},
        {"name":"Riverglide Pathway", "formats":{"Standard": 0.13, "Pioneer": 0.12}},
        {"name":"Roadside Reliquary", "formats":{"Standard": 0.01}},
        {"name":"Rockfall Vale", "formats":{"Standard": 0.09}},
        {"name":"Runeforge Champion", "formats":{"Standard": 0.07}},
        {"name":"Rustvale Bridge", "formats":{"Pauper": 0.14}},
        {"name":"Sacred Foundry", "formats":{"Pioneer": 0.11, "Modern": 0.19}},
        {"name":"Sai, Master Thopterist", "formats":{"Legacy": 0.08}},
        {"name":"Sanctifier en-Vec", "formats":{"Modern": 0.12}},
        {"name":"Sanctum Prelate", "formats":{"Legacy": 0.04}},
        {"name":"Savannah", "formats":{"Legacy": 0.11, "Vintage": 0.05}},
        {"name":"Scalding Tarn", "formats":{"Modern": 0.42, "Legacy": 0.45, "Vintage": 0.59}},
        {"name":"Scattershot Archer", "formats":{"Pauper": 0.05}},
        {"name":"Scavenging Ooze", "formats":{"Modern": 0.05}},
        {"name":"Scoured Barrens", "formats":{"Standard": 0.02}},
        {"name":"Scrubland", "formats":{"Legacy": 0.05, "Vintage": 0.05}},
        {"name":"Sea Gate Oracle", "formats":{"Pauper": 0.09}},
        {"name":"Seasoned Pyromancer", "formats":{"Modern": 0.07}},
        {"name":"Seat of the Synod", "formats":{"Legacy": 0.09, "Vintage": 0.01, "Pauper": 0.12}},
        {"name":"Secluded Steppe", "formats":{"Pauper": 0.04}},
        {"name":"Seeker of the Way", "formats":{"Pauper": 0.16}},
        {"name":"Selfless Spirit", "formats":{"Pioneer": 0.06}},
        {"name":"Sensei's Divining Top", "formats":{"Vintage": 0.34}},
        {"name":"Shacklegeist", "formats":{"Pioneer": 0.05}},
        {"name":"Shadowspear", "formats":{"Modern": 0.10, "Legacy": 0.15}},
        {"name":"Shambling Ghast", "formats":{"Standard": 0.11}},
        {"name":"Shambling Shell", "formats":{"Vintage": 0.07}},
        {"name":"Shardless Agent", "formats":{"Modern": 0.11}},
        {"name":"Shark Typhoon", "formats":{"Pioneer": 0.14}},
        {"name":"Shattered Sanctum", "formats":{"Standard": 0.31}},
        {"name":"Shattering Spree", "formats":{"Vintage": 0.15}},
        {"name":"Shatterskull Smashing", "formats":{"Standard": 0.10}},
        {"name":"Shineshadow Snarl", "formats":{"Standard": 0.03}},
        {"name":"Shipwreck Marsh", "formats":{"Standard": 0.11}},
        {"name":"Showdown of the Skalds", "formats":{"Standard": 0.14}},
        {"name":"Silhana Ledgewalker", "formats":{"Pauper": 0.08}},
        {"name":"Silverbluff Bridge", "formats":{"Pauper": 0.14}},
        {"name":"Silverquill Silencer", "formats":{"Standard": 0.07}},
        {"name":"Silversmote Ghoul", "formats":{"Vintage": 0.03}},
        {"name":"Simian Spirit Guide", "formats":{"Legacy": 0.04}},
        {"name":"Skirk Prospector", "formats":{"Pauper": 0.05}},
        {"name":"Skyclave Apparition", "formats":{"Standard": 0.29, "Pioneer": 0.15, "Legacy": 0.05}},
        {"name":"Slagwoods Bridge", "formats":{"Pauper": 0.01}},
        {"name":"Slippery Bogle", "formats":{"Pauper": 0.08}},
        {"name":"Smoldering Egg", "formats":{"Standard": 0.09}},
        {"name":"Snap", "formats":{"Pauper": 0.09}},
        {"name":"Snapcaster Mage", "formats":{"Modern": 0.07, "Legacy": 0.11, "Vintage": 0.08}},
        {"name":"Snow-Covered Forest", "formats":{"Standard": 0.02, "Modern": 0.11, "Legacy": 0.08, "Pauper": 0.01}},
        {"name":"Snow-Covered Island", "formats":{"Standard": 0.01, "Modern": 0.13, "Legacy": 0.13, "Vintage": 0.13, "Pauper": 0.13}},
        {"name":"Snow-Covered Mountain", "formats":{"Standard": 0.01, "Modern": 0.07, "Vintage": 0.02, "Pauper": 0.09}},
        {"name":"Snow-Covered Plains", "formats":{"Standard": 0.01, "Modern": 0.11, "Legacy": 0.08, "Pauper": 0.06}},
        {"name":"Snow-Covered Swamp", "formats":{"Standard": 0.03, "Pauper": 0.06}},
        {"name":"Snowfield Sinkhole", "formats":{"Standard": 0.01}},
        {"name":"Snuff Out", "formats":{"Pauper": 0.10}},
        {"name":"Sokenzan Smelter", "formats":{"Standard": 0.03}},
        {"name":"Sokenzan, Crucible of Defiance", "formats":{"Standard": 0.15, "Pioneer": 0.23, "Modern": 0.06}},
        {"name":"Sol Ring", "formats":{"Vintage": 0.41}},
        {"name":"Solitude", "formats":{"Modern": 0.20, "Legacy": 0.04}},
        {"name":"Sorin the Mirthless", "formats":{"Standard": 0.28}},
        {"name":"Soul Shatter", "formats":{"Standard": 0.15}},
        {"name":"Soul-Guide Lantern", "formats":{"Modern": 0.12, "Legacy": 0.12, "Vintage": 0.39}},
        {"name":"Soul-Scar Mage", "formats":{"Pioneer": 0.10}},
        {"name":"Spell Pierce", "formats":{"Modern": 0.22, "Legacy": 0.10, "Pauper": 0.12}},
        {"name":"Spellstutter Sprite", "formats":{"Pauper": 0.17}},
        {"name":"Sphinx of the Final Word", "formats":{"Pioneer": 0.04}},
        {"name":"Sphinx of the Steel Wind", "formats":{"Vintage": 0.26}},
        {"name":"Spikefield Hazard", "formats":{"Standard": 0.11}},
        {"name":"Spire Golem", "formats":{"Pauper": 0.05}},
        {"name":"Spirebluff Canal", "formats":{"Pioneer": 0.12, "Modern": 0.18}},
        {"name":"Spirit of the Labyrinth", "formats":{"Legacy": 0.04}},
        {"name":"Spirited Companion", "formats":{"Standard": 0.06}},
        {"name":"Spreading Seas", "formats":{"Modern": 0.10}},
        {"name":"Springleaf Drum", "formats":{"Modern": 0.08}},
        {"name":"Squadron Hawk", "formats":{"Pauper": 0.04}},
        {"name":"Squee, Goblin Nabob", "formats":{"Vintage": 0.03}},
        {"name":"Standard Bearer", "formats":{"Pauper": 0.11}},
        {"name":"Starnheim Unleashed", "formats":{"Standard": 0.11}},
        {"name":"Steam Vents", "formats":{"Pioneer": 0.18, "Modern": 0.43, "Legacy": 0.17}},
        {"name":"Stinkweed Imp", "formats":{"Vintage": 0.07}},
        {"name":"Stitcher's Supplier", "formats":{"Vintage": 0.10}},
        {"name":"Stomping Ground", "formats":{"Pioneer": 0.17, "Modern": 0.25}},
        {"name":"Stonecoil Serpent", "formats":{"Vintage": 0.07}},
        {"name":"Stoneforge Mystic", "formats":{"Modern": 0.07, "Legacy": 0.06}},
        {"name":"Stonehorn Dignitary", "formats":{"Pauper": 0.07}},
        {"name":"Stormbound Geist", "formats":{"Pauper": 0.08}},
        {"name":"Stormcarved Coast", "formats":{"Standard": 0.12, "Pioneer": 0.12}},
        {"name":"Street Wraith", "formats":{"Modern": 0.05, "Vintage": 0.10}},
        {"name":"Strip Mine", "formats":{"Vintage": 0.51}},
        {"name":"Striped Riverwinder", "formats":{"Modern": 0.04}},
        {"name":"Submerge", "formats":{"Legacy": 0.16}},
        {"name":"Subtlety", "formats":{"Modern": 0.10}},
        {"name":"Suffocating Fumes", "formats":{"Pauper": 0.14}},
        {"name":"Sunbaked Canyon", "formats":{"Modern": 0.06}},
        {"name":"Sundering Titan", "formats":{"Modern": 0.05}},
        {"name":"Sundown Pass", "formats":{"Standard": 0.17}},
        {"name":"Sungold Sentinel", "formats":{"Standard": 0.02}},
        {"name":"Sunpetal Grove", "formats":{"Pioneer": 0.07}},
        {"name":"Sunscape Familiar", "formats":{"Pauper": 0.04}},
        {"name":"Supreme Phantom", "formats":{"Pioneer": 0.05}},
        {"name":"Supreme Verdict", "formats":{"Pioneer": 0.16, "Modern": 0.11}},
        {"name":"Surgical Extraction", "formats":{"Legacy": 0.56}},
        {"name":"Swords to Plowshares", "formats":{"Legacy": 0.25, "Vintage": 0.23}},
        {"name":"Sylvan Caryatid", "formats":{"Pioneer": 0.05}},
        {"name":"Sylvan Library", "formats":{"Legacy": 0.08}},
        {"name":"Sylvan Scrying", "formats":{"Pioneer": 0.10}},
        {"name":"Taiga", "formats":{"Legacy": 0.13, "Vintage": 0.03}},
        {"name":"Tainted Adversary", "formats":{"Standard": 0.03}},
        {"name":"Takenuma, Abandoned Mire", "formats":{"Standard": 0.33, "Pioneer": 0.16}},
        {"name":"Tamiyo's Safekeeping", "formats":{"Standard": 0.11}},
        {"name":"Tangled Florahedron", "formats":{"Standard": 0.08}},
        {"name":"Tarmogoyf", "formats":{"Vintage": 0.10}},
        {"name":"Teferi, Hero of Dominaria", "formats":{"Pioneer": 0.14, "Modern": 0.09}},
        {"name":"Teferi, Time Raveler", "formats":{"Modern": 0.25, "Legacy": 0.13}},
        {"name":"Temple Garden", "formats":{"Pioneer": 0.18, "Modern": 0.15}},
        {"name":"Temple of Mystery", "formats":{"Pioneer": 0.10}},
        {"name":"Temporal Trespass", "formats":{"Pioneer": 0.11}},
        {"name":"Terramorphic Expanse", "formats":{"Pauper": 0.03}},
        {"name":"Test of Talents", "formats":{"Standard": 0.19}},
        {"name":"Thalia, Guardian of Thraben", "formats":{"Standard": 0.18, "Legacy": 0.06}},
        {"name":"Thassa's Oracle", "formats":{"Legacy": 0.05, "Vintage": 0.09}},
        {"name":"The Meathook Massacre", "formats":{"Standard": 0.39}},
        {"name":"The Restoration of Eiganjo", "formats":{"Standard": 0.14}},
        {"name":"The Tabernacle at Pendrell Vale", "formats":{"Legacy": 0.08, "Vintage": 0.55}},
        {"name":"The Wandering Emperor", "formats":{"Standard": 0.57, "Pioneer": 0.16}},
        {"name":"Thermo-Alchemist", "formats":{"Pauper": 0.05}},
        {"name":"Thespian's Stage", "formats":{"Pioneer": 0.10, "Legacy": 0.10}},
        {"name":"Thing in the Ice", "formats":{"Pioneer": 0.11}},
        {"name":"Thorn of the Black Rose", "formats":{"Pauper": 0.12}},
        {"name":"Thought Distortion", "formats":{"Pioneer": 0.12}},
        {"name":"Thought Monitor", "formats":{"Legacy": 0.08, "Vintage": 0.02}},
        {"name":"Thoughtcast", "formats":{"Pauper": 0.10}},
        {"name":"Thoughtseize", "formats":{"Pioneer": 0.24, "Modern": 0.19, "Legacy": 0.19}},
        {"name":"Thraben Inspector", "formats":{"Pauper": 0.19}},
        {"name":"Thriving Isle", "formats":{"Pauper": 0.02}},
        {"name":"Time Vault", "formats":{"Vintage": 0.29}},
        {"name":"Time Walk", "formats":{"Vintage": 0.69}},
        {"name":"Timeless Dragon", "formats":{"Legacy": 0.06}},
        {"name":"Tinker", "formats":{"Vintage": 0.31}},
        {"name":"Tireless Tracker", "formats":{"Modern": 0.04}},
        {"name":"Tolarian Academy", "formats":{"Vintage": 0.37}},
        {"name":"Tormod's Crypt", "formats":{"Modern": 0.09}},
        {"name":"Torpor Orb", "formats":{"Legacy": 0.13}},
        {"name":"Tourach, Dread Cantor", "formats":{"Modern": 0.06}},
        {"name":"Tovolar's Huntmaster", "formats":{"Pioneer": 0.11}},
        {"name":"Tranquil Cove", "formats":{"Standard": 0.01, "Pauper": 0.02}},
        {"name":"Treasure Cruise", "formats":{"Pioneer": 0.12, "Vintage": 0.25}},
        {"name":"Tree of Tales", "formats":{"Pauper": 0.01}},
        {"name":"Trinket Mage", "formats":{"Pauper": 0.04}},
        {"name":"Tropical Island", "formats":{"Legacy": 0.14, "Vintage": 0.16}},
        {"name":"True-Name Nemesis", "formats":{"Legacy": 0.05}},
        {"name":"Tundra", "formats":{"Legacy": 0.17, "Vintage": 0.20}},
        {"name":"Ulamog, the Ceaseless Hunger", "formats":{"Modern": 0.04}},
        {"name":"Underground Sea", "formats":{"Legacy": 0.17, "Vintage": 0.51}},
        {"name":"Unexpected Windfall", "formats":{"Standard": 0.10}},
        {"name":"Unholy Heat", "formats":{"Modern": 0.21}},
        {"name":"Urborg, Tomb of Yawgmoth", "formats":{"Pioneer": 0.13, "Modern": 0.09}},
        {"name":"Uro, Titan of Nature's Wrath", "formats":{"Legacy": 0.08}},
        {"name":"Urza, Lord High Artificer", "formats":{"Vintage": 0.05}},
        {"name":"Urza's Bauble", "formats":{"Legacy": 0.08}},
        {"name":"Urza's Mine", "formats":{"Pauper": 0.05}},
        {"name":"Urza's Power Plant", "formats":{"Pauper": 0.05}},
        {"name":"Urza's Saga", "formats":{"Modern": 0.18, "Legacy": 0.20, "Vintage": 0.43}},
        {"name":"Urza's Tower", "formats":{"Pauper": 0.05}},
        {"name":"Usher of the Fallen", "formats":{"Standard": 0.13}},
        {"name":"Valakut, the Molten Pinnacle", "formats":{"Modern": 0.07}},
        {"name":"Valki, God of Lies", "formats":{"Standard": 0.04}},
        {"name":"Valorous Stance", "formats":{"Standard": 0.37}},
        {"name":"Vampiric Tutor", "formats":{"Vintage": 0.43}},
        {"name":"Vanishing Verse", "formats":{"Standard": 0.31}},
        {"name":"Vault of Whispers", "formats":{"Pauper": 0.19}},
        {"name":"Veil of Summer", "formats":{"Modern": 0.20}},
        {"name":"Vengevine", "formats":{"Vintage": 0.12}},
        {"name":"Verdant Catacombs", "formats":{"Modern": 0.11, "Legacy": 0.15, "Vintage": 0.15}},
        {"name":"Violent Outburst", "formats":{"Modern": 0.10}},
        {"name":"Vizier of Tumbling Sands", "formats":{"Pioneer": 0.10}},
        {"name":"Voice of Resurgence", "formats":{"Pioneer": 0.12}},
        {"name":"Volatile Fjord", "formats":{"Pauper": 0.04}},
        {"name":"Volcanic Island", "formats":{"Legacy": 0.45, "Vintage": 0.27}},
        {"name":"Voldaren Epicure", "formats":{"Standard": 0.06, "Pioneer": 0.08, "Pauper": 0.08}},
        {"name":"Waker of Waves", "formats":{"Modern": 0.04}},
        {"name":"Walking Ballista", "formats":{"Modern": 0.09, "Vintage": 0.09}},
        {"name":"Wasteland", "formats":{"Legacy": 0.48, "Vintage": 0.48}},
        {"name":"Watery Grave", "formats":{"Modern": 0.09, "Vintage": 0.02}},
        {"name":"Wear // Tear", "formats":{"Modern": 0.07}},
        {"name":"Weather the Storm", "formats":{"Pauper": 0.12}},
        {"name":"Wedding Announcement", "formats":{"Standard": 0.37}},
        {"name":"Welcoming Vampire", "formats":{"Standard": 0.08}},
        {"name":"Werewolf Pack Leader", "formats":{"Standard": 0.02}},
        {"name":"Wind-Scarred Crag", "formats":{"Pauper": 0.12}},
        {"name":"Windswept Heath", "formats":{"Modern": 0.20, "Legacy": 0.14, "Vintage": 0.10}},
        {"name":"Winota, Joiner of Forces", "formats":{"Pioneer": 0.11}},
        {"name":"Wirewood Symbiote", "formats":{"Legacy": 0.04}},
        {"name":"Witch's Cottage", "formats":{"Pauper": 0.02}},
        {"name":"Wooded Foothills", "formats":{"Modern": 0.27, "Legacy": 0.15, "Vintage": 0.07}},
        {"name":"Woodland Chasm", "formats":{"Standard": 0.02}},
        {"name":"Wrenn and Six", "formats":{"Modern": 0.14}},
        {"name":"Wurmcoil Engine", "formats":{"Modern": 0.06, "Vintage": 0.08}},
        {"name":"Yasharn, Implacable Earth", "formats":{"Standard": 0.11, "Pioneer": 0.05}},
        {"name":"Yavimaya Coast", "formats":{"Pioneer": 0.07}},
        {"name":"Yavimaya, Cradle of Growth", "formats":{"Legacy": 0.12}},
        {"name":"Yawgmoth's Will", "formats":{"Vintage": 0.18}},
        {"name":"Yixlid Jailer", "formats":{"Vintage": 0.06}},
        {"name":"Yorion, Sky Nomad", "formats":{"Modern": 0.10, "Legacy": 0.05}},
        {"name":"Young Pyromancer", "formats":{"Pioneer": 0.05, "Vintage": 0.03}},
    ];
    // @formatter:on
}

function loadVintageRestricted() {
    return {
        "Ancestral Recall": true,
        "Balance": true,
        "Black Lotus": true,
        "Brainstorm": true,
        "Chalice of the Void": true,
        "Channel": true,
        "Demonic Consultation": true,
        "Demonic Tutor": true,
        "Dig Through Time": true,
        "Flash": true,
        "Gitaxian Probe": true,
        "Golgari Grave-Troll": true,
        "Gush": true,
        "Imperial Seal": true,
        "Karn, the Great Creator": true,
        "Library of Alexandria": true,
        "Lion's Eye Diamond": true,
        "Lodestone Golem": true,
        "Lotus Petal": true,
        "Mana Crypt": true,
        "Mana Vault": true,
        "Memory Jar": true,
        "Mental Misstep": true,
        "Merchant Scroll": true,
        "Mind's Desire": true,
        "Monastery Mentor": true,
        "Mox Emerald": true,
        "Mox Jet": true,
        "Mox Pearl": true,
        "Mox Ruby": true,
        "Mox Sapphire": true,
        "Mystical Tutor": true,
        "Mystic Forge": true,
        "Narset, Parter of Veils": true,
        "Necropotence": true,
        "Ponder": true,
        "Sol Ring": true,
        "Strip Mine": true,
        "Thorn of Amethyst": true,
        "Timetwister": true,
        "Time Vault": true,
        "Time Walk": true,
        "Tinker": true,
        "Tolarian Academy": true,
        "Treasure Cruise": true,
        "Trinisphere": true,
        "Vampiric Tutor": true,
        "Wheel of Fortune": true,
        "Windfall": true,
        "Yawgmoth's Will": true
    }
}
